const arrCountry = [


/*

africa		
amer_n
amer_s
antarctic
arctic
asia
europe
eurasia
oceania

*/









/*

https://uk.wikipedia.org/wiki/ISO_3166-1










{
	id: '*',
	title: { ua: '', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 0, year: 2022, },
	area: 0,
},


decl - Декларация о нейтралитете
ind - день независимости
state - день государства
not_exist - не существует

День проголошення

*/




{
	id: 'ukr', our: 1,
	title: { ua: 'Україна', en: 'Ukraine', },
	geo: { capital: 'kyiv', part: 'europe', },
	code: { iso: '804', iso2: 'ua', iso3: 'UKR', ean: '482', phone: '+380', },
	site: { wiki_ua: '%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B0', },
	independence_day: '2408',
	population: { count: 48457000, year: 2001, },
	area: 603700,
},
{
	id: 'rus', our: 1,
	title: { ua: 'Росія', en: 'Russia', },
	geo: { capital: 'moscow', part: 'eurasia', },
	code: { iso: '643', iso2: 'ru', iso3: 'RUS', ean: '460-469', phone: '+7', },
	site: { wiki_ua: '%D0%A0%D0%BE%D1%81%D1%96%D1%8F', },
	independence_day: { dm: '1206', descr: 'state', wiki_ua: '', },
	population: { count: 142998511, year: 2020, },
	area: 17098246,
},
{
	id: 'aze', our: 1,
	title: { ua: 'Азербайджан', en: 'Azerbaijan', },
	geo: { capital: 'baku', part: 'eurasia', },
	code: { iso: '031', iso2: 'az', iso3: 'AZE', ean: '476', phone: '+994', },
	site: { wiki_ua: '%D0%90%D0%B7%D0%B5%D1%80%D0%B1%D0%B0%D0%B9%D0%B4%D0%B6%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'blr', our: 1,
	title: { ua: 'Білорусь', en: 'Belarus', },
	geo: { capital: 'minsk', part: 'europe', },
	code: { iso: '112', iso2: 'by', iso3: 'BLR', ean: '481', phone: '+375', },
	site: { wiki_ua: '%D0%91%D1%96%D0%BB%D0%BE%D1%80%D1%83%D1%81%D1%8C', },
	independence_day: { dm: '0307', descr: '', note: '', wiki_ua: '', },
	population: { count: 9475600, year: 2019, },
	area: 207600,
},
{
	id: 'arm', our: 1,
	title: { ua: 'Вірменія', en: 'Armenia', },
	geo: { capital: 'yerevan', part: 'asia', },
	code: { iso: '051', iso2: 'am', iso3: 'ARM', ean: '485', phone: '+374', },
	site: { wiki_ua: '%D0%92%D1%96%D1%80%D0%BC%D0%B5%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'geo', our: 1,
	title: { ua: 'Грузія', en: 'Georgia', },
	geo: { capital: 'tbilisi', part: 'europe', },
	code: { iso: '268', iso2: 'ge', iso3: 'GEO', ean: '486', phone: '+995', },
	site: { wiki_ua: '%D0%93%D1%80%D1%83%D0%B7%D1%96%D1%8F', },	
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 3729500, year: 2015, },
	area: 69700,
},
{
	id: 'kaz', our: 1,
	title: { ua: 'Казахстан', en: 'Kazakhstan', },
	geo: { capital: 'nur_sultan', part: 'asia', },
	code: { iso: '398', iso2: 'kz', iso3: 'KAZ', ean: '487', phone: '+7', },
	site: { wiki_ua: '%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	note: 'Телефонный код как в России',
},
{
	id: 'kgz', our: 1,
	title: { ua: 'Киргизстан', en: 'Kyrgyzstan', },
	geo: { capital: 'bishkek', part: 'asia', },
	code: { iso: '417', iso2: 'kg', iso3: 'KGZ', ean: '470', phone: '+996', },
	site: { wiki_ua: '%D0%9A%D0%B8%D1%80%D0%B3%D0%B8%D0%B7%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lva', our: 1,
	title: { ua: 'Латвія', en: 'Latvia', },
	geo: { capital: 'riga', part: 'europe', },
	code: { iso: '428', iso2: 'lv', iso3: 'LVA', ean: '475', phone: '+371', },
	site: { wiki_ua: '%D0%9B%D0%B0%D1%82%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ltu', our: 1,
	title: { ua: 'Литва', en: 'Lithuania', },
	geo: { capital: 'vilnius', part: 'europe', },
	code: { iso: '440', iso2: 'lt', iso3: 'LTU', ean: '477', phone: '+370', },
	site: { wiki_ua: '%D0%9B%D0%B8%D1%82%D0%B2%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'mda', our: 1,
	title: { ua: 'Молдова', en: 'Moldova', },
	geo: { capital: 'сhisinau', part: 'europe', },
	code: { iso: '498', iso2: 'md', iso3: 'MDA', ean: '484', phone: '+373', },
	site: { wiki_ua: '%D0%9C%D0%BE%D0%BB%D0%B4%D0%BE%D0%B2%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'tjk', our: 1,
	title: { ua: 'Таджикистан', en: 'Tajikistan', },
	geo: { capital: 'dushanbe', part: 'asia', },
	code: { iso: '762', iso2: 'tj', iso3: 'TJK', ean: '488', phone: '+992', },
	site: { wiki_ua: '%D0%A2%D0%B0%D0%B4%D0%B6%D0%B8%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'tkm', our: 1,
	title: { ua: 'Туркменістан', en: 'Turkmenistan', },
	geo: { capital: 'ashgabat', part: 'asia', },
	code: { iso: '795', iso2: 'tm', iso3: 'TKM', ean: '483', phone: '+993', },
	site: { wiki_ua: '%D0%A2%D1%83%D1%80%D0%BA%D0%BC%D0%B5%D0%BD%D1%96%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'uzb', our: 1,
	title: { ua: 'Узбекистан', en: 'Uzbekistan', },
	geo: { capital: 'tashkent', part: 'asia', },
	code: { iso: '860', iso2: 'uz', iso3: 'UZB', ean: '478', phone: '+998', },
	site: { wiki_ua: '%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'est', our: 1,
	title: { ua: 'Естонія', en: 'Estonia', },
	geo: { capital: 'tallinn', part: 'europe', },
	code: { iso: '233', iso2: 'ee', iso3: 'EST', ean: '474', phone: '+372', },
	site: { wiki_ua: '%D0%95%D1%81%D1%82%D0%BE%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'aus',
	title: { ua: 'Австралія', en: 'Australia', },
	geo: { capital: 'canberra', part: 'oceania', },
	code: { iso: '036', iso2: 'au', iso3: 'AUS', ean: '93', phone: '+61', },
	site: { wiki_ua: '%D0%90%D0%B2%D1%81%D1%82%D1%80%D0%B0%D0%BB%D1%96%D1%8F', },
	independence_day: { dm: '2601', descr: 'state', wiki_ua: '', },
},
{
	id: 'aut',
	title: { ua: 'Австрія', en: 'Austria', },
	geo: { capital: 'wien', part: 'europe', },
	code: { iso: '040', iso2: 'at', iso3: 'AUT', ean: '90-91', phone: '+43', },
	site: { wiki_ua: '%D0%90%D0%B2%D1%81%D1%82%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '2610', descr: 'decl', note: 'Декларация о нейтралитете', },
},
{
	id: 'arg',
	title: { ua: 'Аргентина', en: 'Argentina', },
	geo: { capital: 'buenos_aires', part: 'amer_s', },
	code: { iso: '032', iso2: 'ar', iso3: 'ARG', ean: '779', phone: '+54', },
	site: { wiki_ua: '%D0%90%D1%80%D0%B3%D0%B5%D0%BD%D1%82%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},

{
	id: 'brb',
	title: { ua: 'Барбадос', en: 'Barbados', },
	geo: { capital: 'bridgetown', part: 'amer_n', },
	code: { iso: '', iso2: 'bb', iso3: 'BRB', ean: '', phone: '+1-246', },
	site: { wiki_ua: '%D0%91%D0%B0%D1%80%D0%B1%D0%B0%D0%B4%D0%BE%D1%81', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bel',
	title: { ua: 'Бельгія', en: 'Belgium', },
	geo: { capital: 'brussels', part: 'europe', },
	code: { iso: '056', iso2: 'be', iso3: 'BEL', ean: '54', phone: '+32', },
	site: { wiki_ua: '%D0%91%D0%B5%D0%BB%D1%8C%D0%B3%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bgr',
	title: { ua: 'Болгарія', en: 'Bulgaria', },
	geo: { capital: 'sofia', part: 'europe', },
	code: { iso: '100', iso2: 'bg', iso3: 'BGR', ean: '380', phone: '+359', },
	site: { wiki_ua: '%D0%91%D0%BE%D0%BB%D0%B3%D0%B0%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bra',
	title: { ua: 'Бразилія', en: 'Brazil', },
	geo: { capital: 'brasilia', part: 'amer_s', },
	code: { iso: '076', iso2: 'br', iso3: 'BRA', ean: '789', phone: '+55', },
	site: { wiki_ua: '%D0%91%D1%80%D0%B0%D0%B7%D0%B8%D0%BB%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gbr',
	title: { ua: 'Велика Британія', en: 'United Kingdom', },
	geo: { capital: 'london', part: 'europe', },
	code: { iso: '826', iso2: 'gb', iso3: 'GBR', ean: '50', phone: '+44', },
	site: { wiki_ua: '%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%B0_%D0%91%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'vnm',
	title: { ua: 'В\'єтнам', en: 'Vietnam', },
	geo: { capital: 'hanoi', part: 'asia', },
	code: { iso: '704', iso2: 'vn', iso3: 'VNM', ean: '893', phone: '+84', },
	site: { wiki_ua: '%D0%92%27%D1%94%D1%82%D0%BD%D0%B0%D0%BC', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'hkg',
	title: { ua: 'Гонконг', en: 'Hong Kong', },
	geo: { part: 'asia', },
	code: { iso: '344', iso2: 'hk', iso3: 'HKG', ean: '489', phone: '+852', },
	site: { wiki_ua: '%D0%93%D0%BE%D0%BD%D0%BA%D0%BE%D0%BD%D0%B3', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 7055071, year: 2010, },
	area: 1104,
},
{
	id: 'dnk',
	title: { ua: 'Данія', en: 'Denmark', },
	geo: { capital: 'copenhagen', part: 'europe', },
	code: { iso: '208', iso2: 'dk', iso3: 'DNK', ean: '57', phone: '+45', },
	site: { wiki_ua: '%D0%94%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'dma',
	title: { ua: 'Домініка', en: 'Dominica', },
	geo: { capital: 'rose', part: 'amer_n', },
	code: { iso: '212', iso2: 'dm', iso3: 'DMA', ean: '', phone: '+1767', },
	site: { wiki_ua: '%D0%94%D0%BE%D0%BC%D1%96%D0%BD%D1%96%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'isr',
	title: { ua: 'Ізраїль', en: 'Israel', },
	geo: { capital: 'jerusalem', part: 'asia', },
	code: { iso: '376', iso2: 'il', iso3: 'ISR', ean: '729', phone: '+972', },
	site: { wiki_ua: '%D0%86%D0%B7%D1%80%D0%B0%D1%97%D0%BB%D1%8C', },
	independence_day: { dm: '1405', descr: '', note: '', wiki_ua: '', },
	population: { count: 9291000, year: 2021, },
	area: 20770,
},
{
	id: 'ind',
	title: { ua: 'Індія', en: 'India', },
	geo: { capital: 'new_delhi', part: 'asia', },
	code: { iso: '356', iso2: 'in', iso3: 'IND', ean: '890', phone: '+91', },
	site: { wiki_ua: '%D0%86%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 1414843757, year: 2022, },
	area: 3287590,
},
{
	id: 'irq',
	title: { ua: 'Ірак', en: 'Iraq', },
	geo: { capital: 'baghdad', part: 'asia', },
	code: { iso: '368', iso2: 'iq', iso3: 'IRQ', ean: '', phone: '+964', },
	site: { wiki_ua: '%D0%86%D1%80%D0%B0%D0%BA', },
	independence_day: { dm: '0310', descr: '', note: '', wiki_ua: '', },
	population: { count: 39127900, year: 2019, },
	area: 437072,
},
{
	id: 'irn',
	title: { ua: 'Іран', en: 'Iran', },
	geo: { capital: 'tehran', part: 'asia', },
	code: { iso: '364', iso2: 'ir', iso3: 'IRN', ean: '626', phone: '+98', },
	site: { wiki_ua: '%D0%86%D1%80%D0%B0%D0%BD', },
	independence_day: { dm: '0104', descr: '', note: '', wiki_ua: '', },
	population: { count: 79966230, year: 2017, },
	area: 1648195,
},
{
	id: 'irl',
	title: { ua: 'Ірландія', en: 'Ireland', },
	geo: { capital: 'dublin', part: 'europe', },
	code: { iso: '372', iso2: 'ie', iso3: 'IRL', ean: '539', phone: '+353', },
	site: { wiki_ua: '%D0%86%D1%80%D0%BB%D0%B0%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'esp',
	title: { ua: 'Іспанія', en: 'Spain', },
	geo: { capital: 'madrid', part: 'europe', },
	code: { iso: '724', iso2: 'es', iso3: 'ESP', ean: '84', phone: '+34', },
	site: { wiki_ua: '%D0%86%D1%81%D0%BF%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 47500000, year: 2021, },
	area: 504645,
},
{
	id: 'ita',
	title: { ua: 'Італія', en: 'Italy', },
	geo: { capital: 'rome', part: 'europe', },
	code: { iso: '380', iso2: 'it', iso3: 'ITA', ean: '80-83', phone: '+39', },
	site: { wiki_ua: '%D0%86%D1%82%D0%B0%D0%BB%D1%96%D1%8F', },
	independence_day: { dm: '0206', descr: '', note: 'День проголошення', wiki_ua: '%D0%94%D0%B5%D0%BD%D1%8C_%D0%BF%D1%80%D0%BE%D0%B3%D0%BE%D0%BB%D0%BE%D1%88%D0%B5%D0%BD%D0%BD%D1%8F_%D0%86%D1%82%D0%B0%D0%BB%D1%96%D0%B9%D1%81%D1%8C%D0%BA%D0%BE%D1%97_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B8', },
	population: { count: 60588306, year: 2019, },
	area: 301338,
},
{
	id: 'can',
	title: { ua: 'Канада', en: 'Canada', },
	geo: { capital: 'ottawa', part: 'amer_n', },
	code: { iso: '124', iso2: 'ca', iso3: 'CAN', ean: '', phone: '+1', },
	site: { wiki_ua: '%D0%9A%D0%B0%D0%BD%D0%B0%D0%B4%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 37067011, year: 2018, },
	area: 9984670,	
},
{
	id: 'chn',
	title: { ua: 'Китай', en: 'China', },
	geo: { capital: 'beijing', part: 'asia', },
	code: { iso: '156', iso2: 'cn', iso3: 'CHN', ean: '690-693', phone: '+86', },
	site: { wiki_ua: '%D0%9A%D0%B8%D1%82%D0%B0%D0%B9%D1%81%D1%8C%D0%BA%D0%B0_%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%B0_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 1411780000, year: 2021, },
	area: 9596960,
},
{
	id: 'col',
	title: { ua: 'Колумбія', en: 'Colombia', },
	geo: { capital: 'bogota', part: 'amer_s', },
	code: { iso: '170', iso2: 'co', iso3: 'COL', ean: '770', phone: '+57', },
	site: { wiki_ua: '%D0%9A%D0%BE%D0%BB%D1%83%D0%BC%D0%B1%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cub',
	title: { ua: 'Куба', en: 'Cuba', },
	geo: { capital: 'havana', part: 'amer_n', },
	code: { iso: '192', iso2: 'cu', iso3: 'CUB', ean: '850', phone: '+53', },
	site: { wiki_ua: '%D0%9A%D1%83%D0%B1%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lby',
	title: { ua: 'Лівія', en: 'Libya', },
	geo: { capital: 'tripoli', part: 'africa', },
	code: { iso: '434', iso2: 'ly', iso3: 'LBY', ean: '', phone: '+218', },
	site: { wiki_ua: '%D0%9B%D1%96%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'mex',
	title: { ua: 'Мексика', en: 'Mexico', },
	geo: { capital: 'mexico', part: 'amer_n', },
	code: { iso: '484', iso2: 'mx', iso3: 'MEX', ean: '750', phone: '+52', },
	site: { wiki_ua: '%D0%9C%D0%B5%D0%BA%D1%81%D0%B8%D0%BA%D0%B0', },
	independence_day: { dm: '1609', descr: 'ind', note: '', wiki_ua: '', },
	population: { count: 126577691, year: 2019, },
	area: 1972550,
},
{
	id: 'nld',
	title: { ua: 'Нідерланди', en: 'Netherlands', },
	geo: { capital: 'amsterdam', part: 'europe', },
	code: { iso: '528', iso2: 'nl', iso3: 'NLD', ean: '87', phone: '+31', },
	site: { wiki_ua: '%D0%9D%D1%96%D0%B4%D0%B5%D1%80%D0%BB%D0%B0%D0%BD%D0%B4%D0%B8', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'deu',
	title: { ua: 'Німеччина', en: 'Germany', },
	geo: { capital: 'berlin', part: 'europe', },
	code: { iso: '276', iso2: 'de', iso3: 'DEU', ean: '400-440', phone: '+49', },
	site: { wiki_ua: '%D0%9D%D1%96%D0%BC%D0%B5%D1%87%D1%87%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 83019200, year: 2019, },
	area: 357578,
},
{
	id: 'nzl',
	title: { ua: 'Нова Зеландія', en: 'New Zealand', },
	geo: { capital: 'wellington', part: 'oceania', },
	code: { iso: '554', iso2: 'nz', iso3: 'NZL', ean: '94', phone: '+64', },
	site: { wiki_ua: '%D0%9D%D0%BE%D0%B2%D0%B0_%D0%97%D0%B5%D0%BB%D0%B0%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'nor',
	title: { ua: 'Норвегія', en: 'Norway', },
	geo: { capital: 'oslo', part: 'europe', },
	code: { iso: '578', iso2: 'no', iso3: 'NOR', ean: '70', phone: '+47', },
	site: { wiki_ua: '%D0%9D%D0%BE%D1%80%D0%B2%D0%B5%D0%B3%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'zaf',
	title: { ua: 'ПАР', en: 'Republic of South Africa', },
	geo: { capital: 'cape_town', part: 'africa', },
	code: { iso: '710', iso2: 'za', iso3: 'ZAF', ean: '600-601', phone: '+27', },
	site: { wiki_ua: '%D0%9F%D1%96%D0%B2%D0%B4%D0%B5%D0%BD%D0%BD%D0%BE-%D0%90%D1%84%D1%80%D0%B8%D0%BA%D0%B0%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'per',
	title: { ua: 'Перу', en: 'Peru', },
	geo: { capital: 'lima', part: 'amer_s', },
	code: { iso: '604', iso2: 'pe', iso3: 'PER', ean: '775', phone: '+51', },
	site: { wiki_ua: '%D0%9F%D0%B5%D1%80%D1%83', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'prk',
	title: { ua: 'Північна Корея', en: 'North Korea', },
	geo: { capital: 'pyongyang', part: 'asia', },
	code: { iso: '408', iso2: 'kp', iso3: 'PRK', ean: '867', phone: '+850', },
	site: { wiki_ua: '%D0%9F%D1%96%D0%B2%D0%BD%D1%96%D1%87%D0%BD%D0%B0_%D0%9A%D0%BE%D1%80%D0%B5%D1%8F', },	
	independence_day: { dm: '1508', descr: 'ind', wiki_ua: '', },
},
{
	id: 'pol',
	title: { ua: 'Польща', en: 'Poland', },
	geo: { capital: 'warszawa', part: 'europe', },
	code: { iso: '616', iso2: 'pl', iso3: 'POL', ean: '590', phone: '+48', },
	site: { wiki_ua: '%D0%9F%D0%BE%D0%BB%D1%8C%D1%89%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'pri',
	title: { ua: 'Пуэрто-Рико', en: 'Puerto Rico', },
	geo: { capital: 'san_juan', part: 'amer_n', },
	code: { iso: '630', iso2: 'pr', iso3: 'PRI', ean: '', phone: '+1(787), 1(939)', },
	site: { wiki_ua: '%D0%9F%D1%83%D0%B5%D1%80%D1%82%D0%BE-%D0%A0%D0%B8%D0%BA%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'rou', 
	title: { ua: 'Румунія', en: 'Romania', },
	geo: { capital: 'bucharest', part: 'europe', },
	code: { iso: '642', iso2: 'ro', iso3: 'ROU', ean: '594', phone: '+40', },
	site: { wiki_ua: '%D0%A0%D1%83%D0%BC%D1%83%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'sau',
	title: { ua: 'Саудівська Аравія', en: 'Saudi Arabia', },
	geo: { capital: 'riyadh', part: 'asia', },
	code: { iso: '682', iso2: 'sa', iso3: 'SAU', ean: '628', phone: '+966', },
	site: { wiki_ua: '%D0%A1%D0%B0%D1%83%D0%B4%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B0_%D0%90%D1%80%D0%B0%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'srb', yug: 1,
	title: { ua: 'Сербія', en: 'Serbia', },
	geo: { capital: 'belgrade', part: 'europe', },
	code: { iso: '688', iso2: 'rs', iso3: 'SRB', ean: '', phone: '+381', },
	site: { wiki_ua: '%D0%A1%D0%B5%D1%80%D0%B1%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'sun', our: 1,
	title: { ua: 'СРСР', en: 'USSR', },
	geo: { capital: 'moscow', part: 'eurasia', },
	code: { iso: '810', iso2: 'su', iso3: 'SUN', ean: '', phone: '', },
	site: { wiki_ua: '%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D1%81%D0%BE%D1%8E%D0%B7%D0%BD%D0%B8%D1%85_%D1%80%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA_%D0%A1%D0%A0%D0%A1%D0%A0', },
	independence_day: { dm: '3012', note: 'Подписание договора об образовании СССР', },
	not_exist: 1,
},
{
	id: 'usa',
	title: { ua: 'США', en: 'USA', },
	geo: { capital: 'washington', part: 'amer_n', },
	code: { iso: '840', iso2: 'us', iso3: 'USA', ean: '00-13', phone: '+1', },
	site: { wiki_ua: '%D0%A1%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D1%96_%D0%A8%D1%82%D0%B0%D1%82%D0%B8_%D0%90%D0%BC%D0%B5%D1%80%D0%B8%D0%BA%D0%B8', },
	independence_day: { dm: '0407', descr: 'ind', wiki_ua: '', },
	population: { count: 328915700, year: 2019, },
	area: 9826675,
},
{
	id: 'tur',
	title: { ua: 'Туреччина', en: 'Turkey', },
	geo: { capital: 'ankara', part: 'asia', },
	code: { iso: '792', iso2: 'tr', iso3: 'TUR', ean: '869', phone: '+90', },
	site: { wiki_ua: '%D0%A2%D1%83%D1%80%D0%B5%D1%87%D1%87%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'fra',
	title: { ua: 'Франція', en: 'France', },
	geo: { capital: 'paris', part: 'europe', },
	code: { iso: '250', iso2: 'fr', iso3: 'FRA', ean: '30-37', phone: '+33', },
	site: { wiki_ua: '%D0%A4%D1%80%D0%B0%D0%BD%D1%86%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 66842134, year: 2016, },
	area: 551595,
},
{
	id: 'cze',
	title: { ua: 'Чехія', en: 'Czech Republic', },
	geo: { capital: 'praha', part: 'europe', },
	code: { iso: '203', iso2: 'cz', iso3: 'CZE', ean: '859', phone: '+420', },
	site: { wiki_ua: '%D0%A7%D0%B5%D1%85%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'che',
	title: { ua: 'Швейцарія', en: 'Switzerland', },
	geo: { capital: 'bern', part: 'europe', },
	code: { iso: '756', iso2: 'ch', iso3: 'CHE', ean: '76', phone: '+41', },
	site: { wiki_ua: '%D0%A8%D0%B2%D0%B5%D0%B9%D1%86%D0%B0%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'swe',
	title: { ua: 'Швеція', en: 'Sweden', },
	geo: { capital: 'stockholm', part: 'europe', },
	code: { iso: '752', iso2: 'se', iso3: 'SWE', ean: '73', phone: '+46', },
	site: { wiki_ua: '%D0%A8%D0%B2%D0%B5%D1%86%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'yug',
	title: { ua: 'Югославія', en: 'Yugoslavia', },
	geo: { capital: 'belgrade', part: 'europe', },
	code: { iso: '891', iso2: 'yu', iso3: 'YUG', ean: '860', phone: '+38', },
	site: { wiki_ua: '%D0%AE%D0%B3%D0%BE%D1%81%D0%BB%D0%B0%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	not_exist: 1,
},
{
	id: 'jpn',
	title: { ua: 'Японія', en: 'Japan', },
	geo: { capital: 'tokyo', part: 'asia', },
	code: { iso: '392', iso2: 'jp', iso3: 'JPN', ean: '45, 49', phone: '+81', },
	site: { wiki_ua: '%D0%AF%D0%BF%D0%BE%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 126476461, year: 2020, },
	area: 377972,
},











///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
	id: 'alb',
	title: { ua: 'Албанія', en: 'Albania', },
	geo: { capital: 'tirana', part: 'europe', },
	code: { iso: '008', iso2: 'al', iso3: 'ALB', ean: '530', phone: '+355', },
	site: { wiki_ua: '%D0%90%D0%BB%D0%B1%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'dza',
	title: { ua: 'Алжир', en: 'Algeria', },
	geo: { capital: 'algeria', part: 'africa', },
	code: { iso: '012', iso2: 'dz', iso3: 'DZA', ean: '613', phone: '+213', },
	site: { wiki_ua: '%D0%90%D0%BB%D0%B6%D0%B8%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ago',
	title: { ua: 'Ангола', en: 'Angola', },
	geo: { capital: 'luanda', part: 'africa', },
	code: { iso: '024', iso2: 'ao', iso3: 'AGO', ean: '', phone: '+244', },
	site: { wiki_ua: '%D0%90%D0%BD%D0%B3%D0%BE%D0%BB%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'and',
	title: { ua: 'Андорра', en: 'Andorra', },
	geo: { capital: 'andorra_la_vella', part: 'europe', },
	code: { iso: '020', iso2: 'ad', iso3: 'AND', ean: '', phone: '+376', },
	site: { wiki_ua: '%D0%90%D0%BD%D0%B4%D0%BE%D1%80%D1%80%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'afg',
	title: { ua: 'Афганістан', en: 'Afghanistan', },
	geo: { capital: 'kabul', part: 'asia', },
	code: { iso: '004', iso2: 'af', iso3: 'AFG', ean: '', phone: '+93', },
	site: { wiki_ua: '%D0%90%D1%84%D0%B3%D0%B0%D0%BD%D1%96%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bgd',
	title: { ua: 'Бангладеш', en: 'Bangladesh', },
	geo: { capital: 'dhaka', part: 'asia', },
	code: { iso: '050', iso2: 'bd', iso3: 'BGD', ean: '', phone: '+880', },
	site: { wiki_ua: '%D0%91%D0%B0%D0%BD%D0%B3%D0%BB%D0%B0%D0%B4%D0%B5%D1%88', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bhr',
	title: { ua: 'Бахрейн', en: 'Bahrain', },
	geo: { capital: 'manama', part: 'asia', },
	code: { iso: '048', iso2: 'bh', iso3: 'BHR', ean: '', phone: '+973', },
	site: { wiki_ua: '%D0%91%D0%B0%D1%85%D1%80%D0%B5%D0%B9%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'blz',
	title: { ua: 'Беліз', en: 'Belize', },
	geo: { capital: 'belmopan', part: 'amer_n', },
	code: { iso: '084', iso2: 'bz', iso3: 'BLZ', ean: '', phone: '+501', },
	site: { wiki_ua: '%D0%91%D0%B5%D0%BB%D1%96%D0%B7', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ben',
	title: { ua: 'Бенін', en: 'Benin', },
	geo: { capital: 'porto_novo', part: 'africa', },
	code: { iso: '204', iso2: 'bj', iso3: 'BEN', ean: '', phone: '+229', },
	site: { wiki_ua: '%D0%91%D0%B5%D0%BD%D1%96%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bur',
	title: { ua: 'Бірма', en: 'Burma', },
	geo: { capital: 'naypedo', part: 'asia', },
	code: { iso: '104', iso2: 'bu', iso3: 'BUR', ean: '', phone: '+95', },
	site: { wiki_ua: '%D0%9C%27%D1%8F%D0%BD%D0%BC%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	not_exist: 1,
},
{
	id: 'bol',
	title: { ua: 'Болівія', en: 'Bolivia', },
	geo: { capital: 'sucre', part: 'amer_s', },
	code: { iso: '068', iso2: 'bo', iso3: 'BOL', ean: '', phone: '+591', },
	site: { wiki_ua: '%D0%91%D0%BE%D0%BB%D1%96%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bih',
	title: { ua: 'Боснія і Герцеговина', en: 'Bosnia and Herzegovina', },
	geo: { capital: 'sarajevo', part: 'europe', },
	code: { iso: '070', iso2: 'ba', iso3: 'BIH', ean: '387', phone: '+387', },
	site: { wiki_ua: '%D0%91%D0%BE%D1%81%D0%BD%D1%96%D1%8F_%D1%96_%D0%93%D0%B5%D1%80%D1%86%D0%B5%D0%B3%D0%BE%D0%B2%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bwa',
	title: { ua: 'Ботсвана', en: 'Botswana', },
	geo: { capital: 'gaborone', part: 'africa', },
	code: { iso: '072', iso2: 'bw', iso3: 'BWA', ean: '', phone: '+267', },
	site: { wiki_ua: '%D0%91%D0%BE%D1%82%D1%81%D0%B2%D0%B0%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'brn',
	title: { ua: 'Бруней', en: 'Brunei', },
	geo: { capital: 'bandar_seri_begawan', part: 'asia', },
	code: { iso: '096', iso2: 'bn', iso3: 'BRN', ean: '', phone: '+673', },
	site: { wiki_ua: '%D0%91%D1%80%D1%83%D0%BD%D0%B5%D0%B9', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'btn',
	title: { ua: 'Бутан', en: 'Butane', },
	geo: { capital: 'thimphu', part: 'asia', },
	code: { iso: '064', iso2: 'bt', iso3: 'BTN', ean: '', phone: '+975', },
	site: { wiki_ua: '%D0%91%D1%83%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'vat',
	title: { ua: 'Ватикан', en: 'Vatican', },
	geo: { part: 'europe', },
	code: { iso: '336', iso2: 'va', iso3: 'VAT', ean: '', phone: '+39,+379', },
	site: { wiki_ua: '%D0%92%D0%B0%D1%82%D0%B8%D0%BA%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 800, year: 2007, },
	area: 0.521,
},
{
	id: 'ven',
	title: { ua: 'Венесуела', en: 'Venezuela', },
	geo: { capital: 'caracas', part: 'amer_s', },
	code: { iso: '862', iso2: 've', iso3: 'VEN', ean: '759', phone: '+58', },
	site: { wiki_ua: '%D0%92%D0%B5%D0%BD%D0%B5%D1%81%D1%83%D0%B5%D0%BB%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gab',
	title: { ua: 'Габон', en: 'Gabon', },
	geo: { capital: 'libreville', part: 'africa', },
	code: { iso: '266', iso2: 'ga', iso3: 'GAB', ean: '', phone: '+241', },
	site: { wiki_ua: '%D0%93%D0%B0%D0%B1%D0%BE%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'hti',
	title: { ua: 'Гаїті', en: 'Haiti', },
	geo: { capital: 'port_au_prince', part: 'amer_n', },
	code: { iso: '', iso2: 'ht', iso3: 'HTI', ean: '', phone: '+509', },
	site: { wiki_ua: '%D0%93%D0%B0%D1%97%D1%82%D1%96', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gmb',
	title: { ua: 'Гамбія', en: 'Gambia', },
	geo: { capital: 'banjul', part: 'africa', },
	code: { iso: '270', iso2: 'gm', iso3: 'GMB', ean: '', phone: '+220', },
	site: { wiki_ua: '%D0%93%D0%B0%D0%BC%D0%B1%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gha',
	title: { ua: 'Гана', en: 'Ghana', },
	geo: { capital: 'accra', part: 'africa', },
	code: { iso: '288', iso2: 'gh', iso3: 'GHA', ean: '', phone: '+233', },
	site: { wiki_ua: '%D0%93%D0%B0%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'guy',
	title: { ua: 'Гаяна', en: 'Guyana', },
	geo: { capital: 'georgetown', part: 'amer_s', },
	code: { iso: '328', iso2: 'gy', iso3: 'GUY', ean: '', phone: '+592', },
	site: { wiki_ua: '%D0%93%D0%B0%D1%8F%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gtm',
	title: { ua: 'Гватемала', en: 'Guatemala', },
	geo: { capital: 'guatemala', part: 'amer_n', },
	code: { iso: '320', iso2: 'gt', iso3: 'GTM', ean: '740', phone: '+502', },
	site: { wiki_ua: '%D0%93%D0%B2%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D0%BB%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gin',
	title: { ua: 'Гвінея', en: 'Guinea', },
	geo: { capital: 'conakry', part: 'africa', },
	code: { iso: '324', iso2: 'gn', iso3: 'GIN', ean: '', phone: '+224', },
	site: { wiki_ua: '%D0%93%D0%B2%D1%96%D0%BD%D0%B5%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gnb',
	title: { ua: 'Гвінея-Бісау', en: 'Guinea-Bissau', },
	geo: { capital: 'bissau', part: 'africa', },
	code: { iso: '624', iso2: 'gw', iso3: 'GNB', ean: '', phone: '+245', },
	site: { wiki_ua: '%D0%93%D0%B2%D1%96%D0%BD%D0%B5%D1%8F-%D0%91%D1%96%D1%81%D0%B0%D1%83', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gib',
	title: { ua: 'Гібралтар', en: 'Gibraltar', },
	geo: { capital: '', part: 'europe', },
	code: { iso: '', iso2: 'gi', iso3: 'GIB', ean: '', phone: '+350', },
	site: { wiki_ua: '%D0%93%D1%96%D0%B1%D1%80%D0%B0%D0%BB%D1%82%D0%B0%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'hnd',
	title: { ua: 'Гондурас', en: 'Honduras', },
	geo: { capital: 'tegucigalpa', part: 'amer_n', },
	code: { iso: '', iso2: 'hn', iso3: 'HND', ean: '742', phone: '+504', },
	site: { wiki_ua: '%D0%93%D0%BE%D0%BD%D0%B4%D1%83%D1%80%D0%B0%D1%81', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'grl',
	title: { ua: 'Гренландія', en: 'Greenland', },
	geo: { capital: 'nuuk', part: '', },
	code: { iso: '304', iso2: 'gl', iso3: 'GRL', ean: '', phone: '+299', },
	site: { wiki_ua: '%D0%93%D1%80%D0%B5%D0%BD%D0%BB%D0%B0%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'grc',
	title: { ua: 'Греція', en: 'Greece', },
	geo: { capital: 'athens', part: 'europe', },
	code: { iso: '300', iso2: 'gr', iso3: 'GRC', ean: '520', phone: '+30', },
	site: { wiki_ua: '%D0%93%D1%80%D0%B5%D1%86%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'dji',
	title: { ua: 'Джибуті', en: 'Djibouti', },
	geo: { capital: 'djibouti', part: 'africa', },
	code: { iso: '262', iso2: 'dj', iso3: 'DJI', ean: '', phone: '+253', },
	site: { wiki_ua: '%D0%94%D0%B6%D0%B8%D0%B1%D1%83%D1%82%D1%96', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'egy',
	title: { ua: 'Єгипет', en: 'Egypt', },
	geo: { capital: 'cairo', part: 'africa', },
	code: { iso: '', iso2: 'eg', iso3: 'EGY', ean: '622', phone: '+20', },
	site: { wiki_ua: '%D0%84%D0%B3%D0%B8%D0%BF%D0%B5%D1%82', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'yem',
	title: { ua: 'Ємен', en: 'Yemen', },
	geo: { capital: 'sana', part: 'asia', },
	code: { iso: '', iso2: 'ye', iso3: 'YEM', ean: '', phone: '+967', },
	site: { wiki_ua: '%D0%84%D0%BC%D0%B5%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'zmb',
	title: { ua: 'Замбія', en: 'Zambia', },
	geo: { capital: 'lusaka', part: 'africa', },
	code: { iso: '894', iso2: 'zm', iso3: 'ZMB', ean: '', phone: '+260', },
	site: { wiki_ua: '%D0%97%D0%B0%D0%BC%D0%B1%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'zwe',
	title: { ua: 'Зімбабве', en: 'Zimbabwe', },
	geo: { capital: 'harare', part: 'africa', },
	code: { iso: '716', iso2: 'zw', iso3: 'ZWE', ean: '', phone: '+263', },
	site: { wiki_ua: '%D0%97%D1%96%D0%BC%D0%B1%D0%B0%D0%B1%D0%B2%D0%B5', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'idn',
	title: { ua: 'Індонезія', en: 'Indonesia', },
	geo: { capital: 'jakarta', part: 'asia', },
	code: { iso: '', iso2: 'id', iso3: 'IDN', ean: '899', phone: '+62', },
	site: { wiki_ua: '%D0%86%D0%BD%D0%B4%D0%BE%D0%BD%D0%B5%D0%B7%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'isl',
	title: { ua: 'Ісландія', en: 'Iceland', },
	geo: { capital: 'reykjavik', part: 'europe', },
	code: { iso: '', iso2: 'is', iso3: 'ISL', ean: '569', phone: '+354', },
	site: { wiki_ua: '%D0%86%D1%81%D0%BB%D0%B0%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'jor',
	title: { ua: 'Йорданія', en: 'Jordan', },
	geo: { capital: 'amman', part: 'asia', },
	code: { iso: '', iso2: 'jo', iso3: 'JOR', ean: '625', phone: '+962', },
	site: { wiki_ua: '%D0%99%D0%BE%D1%80%D0%B4%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'khm',
	title: { ua: 'Камбоджа', en: 'Cambodia', },
	geo: { capital: 'phnom_penh', part: 'asia', },
	code: { iso: '116', iso2: 'kh', iso3: 'KHM', ean: '', phone: '+855', },
	site: { wiki_ua: '%D0%9A%D0%B0%D0%BC%D0%B1%D0%BE%D0%B4%D0%B6%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cmr',
	title: { ua: 'Камерун', en: 'Cameroon', },
	geo: { capital: 'yaounde', part: 'africa', },
	code: { iso: '120', iso2: 'cm', iso3: 'CMR', ean: '', phone: '+237', },
	site: { wiki_ua: '%D0%9A%D0%B0%D0%BC%D0%B5%D1%80%D1%83%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'qat',
	title: { ua: 'Катар', en: 'Qatar', },
	geo: { capital: 'doha', part: 'asia', },
	code: { iso: '634', iso2: 'qa', iso3: 'QAT', ean: '', phone: '+974', },
	site: { wiki_ua: '%D0%9A%D0%B0%D1%82%D0%B0%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ken',
	title: { ua: 'Кенія', en: 'Kenya', },
	geo: { capital: 'nairobi', part: 'africa', },
	code: { iso: '404', iso2: 'ke', iso3: 'KEN', ean: '616', phone: '+254', },
	site: { wiki_ua: '%D0%9A%D0%B5%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cyp',
	title: { ua: 'Кіпр', en: 'Cyprus', },
	geo: { capital: 'nicosia', part: 'asia', },
	code: { iso: '196', iso2: 'cy', iso3: 'CYP', ean: '529', phone: '+357', },
	site: { wiki_ua: '%D0%9A%D1%96%D0%BF%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'kir',
	title: { ua: 'Кірибаті', en: 'Kiribati', },
	geo: { capital: 'south_tarawa', part: 'oceania', },
	code: { iso: '296', iso2: 'ki', iso3: 'KIR', ean: '', phone: '+686', },
	site: { wiki_ua: '%D0%9A%D1%96%D1%80%D0%B8%D0%B1%D0%B0%D1%82%D1%96', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cod',
	title: { ua: 'ДР Конго', en: 'Democratic Republic of the Congo', },
	geo: { capital: 'kinshasa', part: 'africa', },
	code: { iso: '180', iso2: 'cd', iso3: 'COD', ean: '', phone: '+243', },
	site: { wiki_ua: '%D0%94%D0%B5%D0%BC%D0%BE%D0%BA%D1%80%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D0%B0_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0_%D0%9A%D0%BE%D0%BD%D0%B3%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cog',
	title: { ua: 'Конго', en: 'Republic of the Congo', },
	geo: { capital: 'brazzaville', part: 'africa', },
	code: { iso: '178', iso2: 'cg', iso3: 'COG', ean: '', phone: '+242', },
	site: { wiki_ua: '%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0_%D0%9A%D0%BE%D0%BD%D0%B3%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cri',
	title: { ua: 'Коста-Рика', en: 'Costa Rica', },
	geo: { capital: 'san_jose', part: 'amer_n', },
	code: { iso: '188', iso2: 'cr', iso3: 'CRI', ean: '744', phone: '+506', },
	site: { wiki_ua: '%D0%9A%D0%BE%D1%81%D1%82%D0%B0-%D0%A0%D0%B8%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'civ',
	title: { ua: 'Кот-д\'Ивуар', en: 'Ivory Coast', },
	geo: { capital: 'yamoussoukro', part: 'africa', },
	code: { iso: '384', iso2: 'ci', iso3: 'CIV', ean: '', phone: '+225', },
	site: { wiki_ua: '%D0%9A%D0%BE%D1%82-%D0%B4%27%D0%86%D0%B2%D1%83%D0%B0%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'kwt',
	title: { ua: 'Кувейт', en: 'Kuwait', },
	geo: { capital: 'el_kuwait', part: 'asia', },
	code: { iso: '414', iso2: 'kw', iso3: 'KWT', ean: '', phone: '+965', },
	site: { wiki_ua: '%D0%9A%D1%83%D0%B2%D0%B5%D0%B9%D1%82', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lao',
	title: { ua: 'Лаос', en: 'Laos', },
	geo: { capital: 'vientiane', part: 'asia', },
	code: { iso: '418', iso2: 'la', iso3: 'LAO', ean: '', phone: '+856', },
	site: { wiki_ua: '%D0%9B%D0%B0%D0%BE%D1%81', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lso',
	title: { ua: 'Лесото', en: 'Lesotho', },
	geo: { capital: 'maseru', part: 'africa', },
	code: { iso: '426', iso2: 'ls', iso3: 'LSO', ean: '', phone: '+266', },
	site: { wiki_ua: '%D0%9B%D0%B5%D1%81%D0%BE%D1%82%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lbr',
	title: { ua: 'Ліберія', en: 'Liberia', },
	geo: { capital: 'monrovia', part: 'africa', },
	code: { iso: '430', iso2: 'lr', iso3: 'LBR', ean: '', phone: '+231', },
	site: { wiki_ua: '%D0%9B%D1%96%D0%B1%D0%B5%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lbn',
	title: { ua: 'Ліван', en: 'Lebanon', },
	geo: { capital: 'beirut', part: 'asia', },
	code: { iso: '422', iso2: 'lb', iso3: 'LBN', ean: '528', phone: '+961', },
	site: { wiki_ua: '%D0%9B%D1%96%D0%B2%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lie',
	title: { ua: 'Ліхтенштейн', en: 'Liechtenstein', },
	geo: { capital: 'vaduz', part: 'europe', },
	code: { iso: '438', iso2: 'li', iso3: 'LIE', ean: '', phone: '+423', },
	site: { wiki_ua: '%D0%9B%D1%96%D1%85%D1%82%D0%B5%D0%BD%D1%88%D1%82%D0%B5%D0%B9%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lux',
	title: { ua: 'Люксембург', en: 'Luxembourg', },
	geo: { capital: 'luxembourg', part: 'europe', },
	code: { iso: '442', iso2: 'lu', iso3: 'LUX', ean: '54', phone: '+352', },
	site: { wiki_ua: '%D0%9B%D1%8E%D0%BA%D1%81%D0%B5%D0%BC%D0%B1%D1%83%D1%80%D0%B3', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'mrt',
	title: { ua: 'Мавританія', en: 'Mauritania', },
	geo: { capital: 'nouakchott', part: 'africa', },
	code: { iso: '478', iso2: 'mr', iso3: 'MRT', ean: '', phone: '+222', },
	site: { wiki_ua: '%D0%9C%D0%B0%D0%B2%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 3359185, year: 2012, },
	area: 1030700,
},
{
	id: 'mdg',
	title: { ua: 'Мадагаскар', en: 'Madagascar', },
	geo: { capital: 'antananarivo', part: 'africa', },
	code: { iso: '450', iso2: 'mg', iso3: 'MDG', ean: '', phone: '+261', },
	site: { wiki_ua: '%D0%9C%D0%B0%D0%B4%D0%B0%D0%B3%D0%B0%D1%81%D0%BA%D0%B0%D1%80', },
	independence_day: { dm: '2606', descr: '', note: '', wiki_ua: '', },
	population: { count: 26262313, year: 2019, },
	area: 587041,
},
{
	id: 'mkd',
	title: { ua: 'Македонія', en: 'Macedonia', },
	geo: { capital: 'skopje', part: 'europe', },
	code: { iso: '807', iso2: 'mk', iso3: 'MKD', ean: '531', phone: '+389', },
	site: { wiki_ua: '%D0%9F%D1%96%D0%B2%D0%BD%D1%96%D1%87%D0%BD%D0%B0_%D0%9C%D0%B0%D0%BA%D0%B5%D0%B4%D0%BE%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 2103721, year: 2017, },
	area: 25713,
},
{
	id: 'mys',
	title: { ua: 'Малайзія', en: 'Malaysia', },
	geo: { capital: 'kuala_lumpur', part: 'asia', },
	code: { iso: '', iso2: 'my', iso3: 'MYS', ean: '955', phone: '+60', },
	site: { wiki_ua: '%D0%9C%D0%B0%D0%BB%D0%B0%D0%B9%D0%B7%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'mli',
	title: { ua: 'Малі', en: 'Mali', },
	geo: { capital: 'bamako', part: 'africa', },
	code: { iso: '466', iso2: 'ml', iso3: 'MLI', ean: '', phone: '+223', },
	site: { wiki_ua: '%D0%9C%D0%B0%D0%BB%D1%96', },
	independence_day: { dm: '2209', descr: '', note: '', wiki_ua: '', },
	population: { count: 20250833, year: 2020, },
	area: 1240192,
},
{
	id: '*',
	title: { ua: 'Мальта', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '535', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Марокко', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '611', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Мозамбик', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Монако', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Монголия', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'mmr',
	title: { ua: 'Мьянма', en: 'Myanmar', },
	geo: { capital: '', part: '', },
	code: { iso: '104', iso2: 'mm', iso3: 'MMR', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Намибия', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Непал', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Нигер', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Нигерия', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'nic',
	title: { ua: 'Нікарагуа', en: 'Nicaragua', },
	geo: { capital: 'managua', part: 'amer_n', },
	code: { iso: '558', iso2: 'ni', iso3: 'NIC', ean: '743', phone: '+505', },
	site: { wiki_ua: '%D0%9D%D1%96%D0%BA%D0%B0%D1%80%D0%B0%D0%B3%D1%83%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'are',
	title: { ua: 'ОАЕ', en: 'UAE', },
	geo: { capital: 'abu_dhabi', part: 'asia', },
	code: { iso: '784', iso2: 'ae', iso3: 'ARE', ean: '', phone: '+971', },
	site: { wiki_ua: '%D0%9E%D0%B1%27%D1%94%D0%B4%D0%BD%D0%B0%D0%BD%D1%96_%D0%90%D1%80%D0%B0%D0%B1%D1%81%D1%8C%D0%BA%D1%96_%D0%95%D0%BC%D1%96%D1%80%D0%B0%D1%82%D0%B8', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Оман', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Пакистан', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Палестина', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Панама', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '745', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Папуа — Новая Гвинея', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Парагвай', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '784', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'kor',
	title: { ua: 'Південна Корея', en: 'South Korea', },
	geo: { capital: 'seoul', part: 'asia', },
	code: { iso: '410', iso2: 'kr', iso3: 'KOR', ean: '880', phone: '+82', },
	site: { wiki_ua: '%D0%9F%D1%96%D0%B2%D0%B4%D0%B5%D0%BD%D0%BD%D0%B0_%D0%9A%D0%BE%D1%80%D0%B5%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Португалия', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '560', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Руанда', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Сальвадор', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '741', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Самоа', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Сан-Марино', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Сенегал', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'sgp',
	title: { ua: 'Сінгапур', en: 'Singapore', },
	geo: { capital: '', part: 'asia', },
	code: { iso: '702', iso2: 'sg', iso3: 'SGP', ean: '888', phone: '', },
	site: { wiki_ua: '%D0%A1%D1%96%D0%BD%D0%B3%D0%B0%D0%BF%D1%83%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Сирия', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '621', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'svk',
	title: { ua: 'Словакия', en: 'Slovakia', },
	geo: { capital: '', part: '', },
	code: { iso: '703', iso2: 'sk', iso3: 'SVK', ean: '858', phone: '+421', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*', yug: 1,
	title: { ua: 'Словения', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '383', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Сомали', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Судан', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Суринам', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Сьерра-Леоне', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Таиланд', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '885', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'twn',
	title: { ua: 'Тайвань', en: 'Taiwan', },
	geo: { capital: '', part: '', },
	code: { iso: '158', iso2: 'tw', iso3: 'TWN', ean: '471', phone: '+886', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Танзания', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Того', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Тринидад и Тобаго', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Тувалу', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Тунис', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '619', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Уганда', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'hun',
	title: { ua: 'Угорщина', en: 'Hungary', },
	geo: { capital: 'budapest', part: 'europe', },
	code: { iso: '348', iso2: 'hu', iso3: 'HUN', ean: '599', phone: '+36', },
	site: { wiki_ua: '%D0%A3%D0%B3%D0%BE%D1%80%D1%89%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Уругвай', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '773', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Фиджи', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Филиппины', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '480', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'fin',
	title: { ua: 'Фінляндія', en: 'Finland', },
	geo: { capital: '', part: '', },
	code: { iso: '246', iso2: 'fi', iso3: 'FIN', ean: '64', phone: '+358', },
	site: { wiki_ua: '%D0%A4%D1%96%D0%BD%D0%BB%D1%8F%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'hrv', yug: 1,
	title: { ua: 'Хорватия', en: 'Croatia', },
	geo: { capital: '', part: '', },
	code: { iso: '191', iso2: 'hr', iso3: 'HRV', ean: '385', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'ЦАР', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Чад', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'mne', yug: 1,
	title: { ua: 'Черногория', en: 'Montenegro', },
	geo: { capital: '', part: '', },
	code: { iso: '499', iso2: 'me', iso3: 'MNE', ean: '', phone: '+382', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'csk',
	title: { ua: 'Чехословакия', en: 'Czechoslovakia', },
	geo: { capital: '', part: '', },
	code: { iso: '200', iso2: 'cs', iso3: 'CSK', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Чили', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '780', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Шри-Ланка', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '479', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Эквадор', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '786', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Экваториальная Гвинея', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Эритрея', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Эфиопия', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Южный Судан', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: '*',
	title: { ua: 'Ямайка', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	site: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},











];





let objCountry = {};
arrCountry.forEach( k => {
	objCountry[ k.id ] = k;
});






/*


Бар-Код	
https://romario-auto.com/pages/news/74/


609	Маврикий
746	Доминиканская Республика
958	Макау





Телефоны

https://www.ixbt.com/mobile/country_code.html

https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D0%BA%D0%BE%D0%B4%D1%8B_%D1%81%D1%82%D1%80%D0%B0%D0%BD







*/






