const arrNames = [

// при формировании объекта objNames идентификаторами делать английские имена, но с маленькой буквы





{ ua: 'Аббяс' 		, en: 'Abbyas' 		, p: [{ ua: 'Аббясівна' 		, en: 'Abbyasovna' 		, }, { ua: 'Аббясович' 		, en: 'Abbyasovich' 	, }, ], },
{ ua: 'Агіль' 		, en: 'Agil' 		, p: [{ ua: 'Агіліївна' 		, en: 'Agilyevna' 		, }, { ua: 'Агілійович' 	, en: 'Agilyevich' 		, }, ], },
{ ua: 'Ада' 		, en: 'Ada' 		, },
{ ua: 'Олександр' 	, en: 'Alexandr' 	, p: [{ ua: 'Олександрівна' 	, en: 'Alexandrovna' 	, }, { ua: 'Олександрович' 	, en: 'Alexandrovich' 	, }, ], },
{ ua: 'Олександра' 	, en: 'Alexandra' 	, },
{ ua: 'Олексій' 	, en: 'Alexey' 		, p: [{ ua: 'Олексіївна' 		, en: 'Alexeevna' 		, }, { ua: 'Олексійович' 	, en: 'Alexeevich' 		, }, ], },
{ ua: 'Олена' 		, en: 'Alena' 		, },
{ ua: 'Алі' 		, en: 'Ali' 		, p: [{ ua: 'Аліївна' 			, en: 'Alievna' 		, }, { ua: 'Алієвич' 		, en: 'Alievich' 		, }, ], },
{ ua: 'Аліка' 		, en: 'Alika' 		, },
{ ua: 'Аліна' 		, en: 'Alina' 		, },
{ ua: 'Аліса' 		, en: 'Alisa' 		, },
{ ua: 'Алла' 		, en: 'Alla' 		, },
{ ua: 'Анастасія' 	, en: 'Anastasia' 	, },
{ ua: 'Анатолій' 	, en: 'Anatoly' 	, p: [{ ua: 'Анатоліївна' 		, en: 'Anatolyevna' 	, }, { ua: 'Анатолійович' 	, en: 'Anatolyevich' 	, }, ], },
{ ua: 'Ангеліна' 	, en: 'Angelina' 	, },
{ ua: 'Андрій' 		, en: 'Andrey' 		, p: [{ ua: 'Андріївна' 		, en: 'Andreevna' 		, }, { ua: 'Андрійович' 	, en: 'Andreevich' 		, }, ], },
{ ua: 'Ганна' 		, en: 'Anna' 		, },
{ ua: 'Антон' 		, en: 'Anton' 		, p: [{ ua: 'Антонівна' 		, en: 'Antonovna' 		, }, { ua: 'Антонович' 		, en: 'Antonovich' 		, }, ], },
{ ua: 'Антоніна' 	, en: 'Antonina' 	, },
{ ua: 'Анфіса' 		, en: 'Anfisa' 		, },
{ ua: 'Аріф' 		, en: 'Arif' 		, p: [{ ua: 'Аріфівна' 			, en: 'Arifovna' 		, }, { ua: 'Аріфович' 		, en: 'Arifovich' 		, }, ], },
{ ua: 'Армен' 		, en: 'Armen' 		, p: [{ ua: 'Арменівна' 		, en: 'Armenovna' 		, }, { ua: 'Арменович' 		, en: 'Armenovich' 		, }, ], },
{ ua: 'Арніс' 		, en: 'Arnis' 		, p: [{ ua: 'Арнісівна' 		, en: 'Arnisovna' 		, }, { ua: 'Арнісович' 		, en: 'Arnisovich' 		, }, ], },
{ ua: 'Арсен' 		, en: 'Arsen' 		, p: [{ ua: 'Арсенівна' 		, en: 'Arsenovna' 		, }, { ua: 'Арсенович' 		, en: 'Arsenovich' 		, }, ], },
{ ua: 'Артем' 		, en: 'Artem' 		, p: [{ ua: 'Артемівна' 		, en: 'Artemovna' 		, }, { ua: 'Артемович' 		, en: 'Artemovich' 		, }, ], },
{ ua: 'Артур' 		, en: 'Artur' 		, p: [{ ua: 'Артурівна' 		, en: 'Arturovna' 		, }, { ua: 'Артурович' 		, en: 'Arturovich' 		, }, ], },
{ ua: 'Арутюн' 		, en: 'Arutyun' 	, p: [{ ua: 'Арутюнівна' 		, en: 'Arutyunovna' 	, }, { ua: 'Арутюнович' 	, en: 'Arutyunovich' 	, }, ], },
{ ua: 'Арчіл' 		, en: 'Archil' 		, p: [{ ua: 'Арчилівна' 		, en: 'Archilovna' 		, }, { ua: 'Арчилович' 		, en: 'Archilovich' 	, }, ], },
{ ua: 'Богдан' 		, en: 'Bogdan' 		, p: [{ ua: 'Богданінав' 		, en: 'Bogdanovna' 		, }, { ua: 'Богданович' 	, en: 'Bogdanovich' 	, }, ], },
{ ua: 'Богдана' 	, en: 'Bogdana' 	, },
{ ua: 'Борис' 		, en: 'Boris' 		, p: [{ ua: 'Борисівна' 		, en: 'Borisovna' 		, }, { ua: 'Борисович' 		, en: 'Borisovich' 		, }, ], },
{ ua: 'Борислав' 	, en: 'Borislav' 	, p: [{ ua: 'Бориславівна' 		, en: 'Borislavovna' 	, }, { ua: 'Бориславович' 	, en: 'Borislavovich' 	, }, ], },
{ ua: 'Ваак' 		, en: 'Vaak' 		, p: [{ ua: 'Вааківна' 			, en: 'Vaakovna' 		, }, { ua: 'Ваакович' 		, en: 'Vaakovich' 		, }, ], },
{ ua: 'Вадим' 		, en: 'Vadim' 		, p: [{ ua: 'Вадимівна' 		, en: 'Vadimovna' 		, }, { ua: 'Вадимович' 		, en: 'Vadimovich' 		, }, ], },
{ ua: 'Валдіс' 		, en: 'Valdis' 		, p: [{ ua: 'Валдісівна' 		, en: 'Valdisovna' 		, }, { ua: 'Валдісович' 	, en: 'Valdisovich' 	, }, ], },
{ ua: 'Валентин' 	, en: 'Valentin' 	, p: [{ ua: 'Валентинівна' 		, en: 'Valentinovna' 	, }, { ua: 'Валентинович' 	, en: 'Valentinovich' 	, }, ], },
{ ua: 'Валентина' 	, en: 'Valentina' 	, },
{ ua: 'Валерій' 	, en: 'Valery' 		, p: [{ ua: 'Валеріївна' 		, en: 'Valeryevna' 		, }, { ua: 'Валерійович' 	, en: 'Valeryevich' 	, }, ], },
{ ua: 'Валерій' 	, en: 'Valeria' 	, },
{ ua: 'Василій' 	, en: 'Vasily' 		, p: [{ ua: 'Василівна' 		, en: 'Vasilyevna' 		, }, { ua: 'Васильович' 	, en: 'Vasilyevich' 	, }, ], },
{ ua: 'Віра' 		, en: 'Vera' 		, },
{ ua: 'Віктор' 		, en: 'Viktor' 		, p: [{ ua: 'Вікторівна' 		, en: 'Viktorovna' 		, }, { ua: 'Вікторович' 	, en: 'Viktorovich' 	, }, ], },
{ ua: 'Вікторія' 	, en: 'Viktoria' 	, },
{ ua: 'Віталій' 	, en: 'Vitaly' 		, p: [{ ua: 'Віталіївна' 		, en: 'Vitalyevna' 		, }, { ua: 'Віталійович' 	, en: 'Vitalyevich' 	, }, ], },
{ ua: 'Вітольд' 	, en: 'Vitold' 		, p: [{ ua: 'Вітольдівна' 		, en: 'Vitoldovna' 		, }, { ua: 'Вітольдович' 	, en: 'Vitoldovich' 	, }, ], },
{ ua: 'Володимир' 	, en: 'Vladimir' 	, p: [{ ua: 'Володимирівна' 	, en: 'Vladimirovna' 	, }, { ua: 'Володимирович' 	, en: 'Vladimirovich'	, }, ], },
{ ua: 'Владислав' 	, en: 'Vladislav' 	, p: [{ ua: 'Владиславівна' 	, en: 'Vladislavovna' 	, }, { ua: 'Владиславович' 	, en: 'Vladislavovich' 	, }, ], },
{ ua: 'В\'ячеслав' 	, en: 'Vyacheslav' 	, p: [{ ua: 'В\'ячеславівна' 	, en: 'Vyacheslavovna' 	, }, { ua: 'В\'ячеславович' , en: 'Vyacheslavovich' , }, ], },
{ ua: 'Галина' 		, en: 'Galina' 		, },
{ ua: 'Гарік' 		, en: 'Garik' 		, p: [{ ua: 'Гаріківна' 		, en: 'Garikovna' 		, }, { ua: 'Гарікович' 		, en: 'Garikovich' 		, }, ], },
{ ua: 'Геннадій' 	, en: 'Gennady' 	, p: [{ ua: 'Геннадіївна' 		, en: 'Gennadyevna' 	, }, { ua: 'Геннадійович' 	, en: 'Gennadyevich' 	, }, ], },
{ ua: 'Георгій' 	, en: 'Georgy' 		, p: [{ ua: 'Георгіївна' 		, en: 'Georgyevna' 		, }, { ua: 'Георгійович' 	, en: 'Georgievich' 	, }, ], },
{ ua: 'Гліб' 		, en: 'Gleb' 		, p: [{ ua: 'Глібівна' 			, en: 'Glebovna' 		, }, { ua: 'Глібович' 		, en: 'Glebovich' 		, }, ], },
{ ua: 'Готліб' 		, en: 'Gotlib' 		, p: [{ ua: 'Готлібівна' 		, en: 'Gotlibovna' 		, }, { ua: 'Готлібович' 	, en: 'Golibovich' 		, }, ], },
{ ua: 'Гоша' 		, en: 'Gosha' 		, p: [{ ua: 'Гошівна' 			, en: 'Goshevna' 		, }, { ua: 'Гошевич' 		, en: 'Goshevich' 		, }, ], },
{ ua: 'Григорій' 	, en: 'Grigory' 	, p: [{ ua: 'Григорівна' 		, en: 'Grigoryevna' 	, }, { ua: 'Григорович' 	, en: 'Grigoryevich' 	, }, ], },
{ ua: 'Давид' 		, en: 'David' 		, p: [{ ua: 'Давидівна' 		, en: 'Davidovna' 		, }, { ua: 'Давидович' 		, en: 'Davidovich' 		, }, ], },
{ ua: 'Дамир' 		, en: 'Damir' 		, p: [{ ua: 'Дамирівна' 		, en: 'Damir' 			, }, { ua: 'Дамирович' 		, en: 'Damirovich' 		, }, ], },
{ ua: 'Данило' 		, en: 'Daniil' 		, p: [{ ua: 'Даніїлівна' 		, en: 'Daniilovna' 		, }, { ua: 'Данилович'  	, en: 'Daniilovich' 	, }, ], },
{ ua: 'Данило' 		, en: 'Danil' 		, p: [{ ua: 'Данилівна' 		, en: 'Danilovna' 		, }, { ua: 'Данилович' 		, en: 'Daniilovich' 	, }, ], },
{ ua: 'Данило' 		, en: 'Danila' 		, p: [{ ua: 'Данилівна' 		, en: 'Danilovna' 		, }, { ua: 'Данилович' 		, en: 'Danilovich' 		, }, ], },
{ ua: 'Дарина' 		, en: 'Darina' 		, },
{ ua: 'Дар\'я' 		, en: 'Daria' 		, },
{ ua: 'Дато' 		, en: 'Dato' 		, p: [{ ua: 'Датоївна' 			, en: 'Datoevna' 		, }, { ua: 'Датоєвич' 		, en: 'Datoevich' 		, }, ], },
{ ua: 'Денис' 		, en: 'Denis' 		, p: [{ ua: 'Денисівна' 		, en: 'Denisovna' 		, }, { ua: 'Денисович' 		, en: 'Denisovich' 		, }, ], },
{ ua: 'Джаміля' 	, en: 'Jamilya' 	, },
{ ua: 'Джеїран' 	, en: 'Jeiran' 		, p: [{ ua: 'Джейранівна' 		, en: 'Jeiranovna' 		, }, { ua: 'Джеїранович' 	, en: 'Jeiranovich' 	, }, ], },
{ ua: 'Діана' 		, en: 'Diana' 		, },
{ ua: 'Дмитро' 		, en: 'Dmitry' 		, p: [{ ua: 'Дмитрівна' 		, en: 'Dmitrevna' 		, }, { ua: 'Дмитрович' 		, en: 'Dmitrevich' 		, }, ], },
{ ua: 'Донатас' 	, en: 'Donatas' 	, p: [{ ua: 'Донатасівна' 		, en: 'Donatasovna' 	, }, { ua: 'Донатасович' 	, en: 'Donatasovich' 	, }, ], },
{ ua: 'Євген' 		, en: 'Eugeny' 		, p: [{ ua: 'Євгенівна' 		, en: 'Eugenevna' 		, }, { ua: 'Євгенович' 		, en: 'Eugenevich' 		, }, ], },
{ ua: 'Євгенія' 	, en: 'Eugenia'		, },
{ ua: 'Єгор'		, en: 'Egor' 		, p: [{ ua: 'Єгорівна' 			, en: 'Egorovna' 		, }, { ua: 'Єгорович' 		, en: 'Egorovich' 		, }, ], },
{ ua: 'Катерина' 	, en: 'Ekaterina' 	, },
{ ua: 'Олена' 		, en: 'Elena' 		, },
{ ua: 'Єлизавета' 	, en: 'Elizaveta' 	, },
{ ua: 'Жанна' 		, en: 'Janna' 		, },
{ ua: 'Захар' 		, en: 'Zahar' 		, p: [{ ua: 'Захарівна' 		, en: 'Zaharovna' 		, }, { ua: 'Захарович' 		, en: 'Zaharvich' 		, }, ], },
{ ua: 'Зіновій' 	, en: 'Zinovy' 		, p: [{ ua: 'Зіновіївна' 		, en: 'Zinovevna' 		, }, { ua: 'Зіновійович' 	, en: 'Zinovevich' 		, }, ], },
{ ua: 'Злата'		, en: 'Zlata' 		, },
{ ua: 'Зоя' 		, en: 'Zoya' 		, },
{ ua: 'Іван' 		, en: 'Ivan' 		, p: [{ ua: 'Іванівна' 		, en: 'Ivanovna' 		, }, { ua: 'Іванович' 		, en: 'Ivanovich' 		, }, ], },
{ ua: 'Ігнат' 		, en: 'Ignat' 		, p: [{ ua: 'Ігнатівна' 	, en: 'Ignatovna' 		, }, { ua: 'Ігнатович' 		, en: 'Ignatovich' 		, }, ], },
{ ua: 'Ігор' 		, en: 'Igor' 		, p: [{ ua: 'Ігорівана' 	, en: 'Igorevna' 		, }, { ua: 'Ігорович' 		, en: 'Igorevich' 		, }, ], },
{ ua: 'Іларіон' 	, en: 'Ilarion' 	, p: [{ ua: 'Ілвріонівна' 	, en: 'Ilarionщмтф' 	, }, { ua: 'Іларіонович' 	, en: 'Ilarionovich' 	, }, ], },
{ ua: 'Ілля' 		, en: 'Ilya' 		, p: [{ ua: 'Іллівна' 		, en: 'Ilinichna' 		, }, { ua: 'Ілліч' 			, en: 'Ilich' 			, }, ], },
{ ua: 'Інна' 		, en: 'Inna' 		, },
{ ua: 'Інокентій' 	, en: 'Innokenty' 	, p: [{ ua: 'Інокентіївна' 	, en: 'Innokentevna' 	, }, { ua: 'Інокентійович' 	, en: 'Innokentevich' 	, }, ], },
{ ua: 'Йосип' 		, en: 'Iosif' 		, p: [{ ua: 'Йосипівна' 	, en: 'Iosifovna' 		, }, { ua: 'Йосипович' 		, en: 'Iosifovich' 		, }, ], },
{ ua: 'Іполит' 		, en: 'Ippolit' 	, p: [{ ua: 'Іполитівна' 	, en: 'Ippolit' 		, }, { ua: 'Іполитович' 	, en: 'Ippolitovich' 	, }, ], },
{ ua: 'Ірина' 		, en: 'Irina' 		, },
{ ua: 'Карина' 		, en: 'Karina' 		, },
{ ua: 'Кір' 		, en: 'Kir' 		, p: [{ ua: 'Кіровна' 		, en: 'Kirovna' 		, }, { ua: 'Кірович' 		, en: 'Kirovich' 		, }, ], },
{ ua: 'Кирило' 		, en: 'Kirill' 		, p: [{ ua: 'Кирилівна' 	, en: 'Kirillovna' 		, }, { ua: 'Кирилович' 		, en: 'Kirillovich' 	, }, ], },
{ ua: 'Клара'		, en: 'Klara' 		, },
{ ua: 'Костянтин' 	, en: 'Konstantin' 	, p: [{ ua: 'Костянтинівна' , en: 'Konstantin' 		, }, { ua: 'Костянтинович' 	, en: 'Konstantinvich' 	, }, ], },
{ ua: 'Корнелій' 	, en: 'Kornely' 	, p: [{ ua: 'Корнелівна' 	, en: 'Kornelevna' 		, }, { ua: 'Корнельович' 	, en: 'Kornelevich' 	, }, ], },
{ ua: 'Христина' 	, en: 'Kristina' 	, },
{ ua: 'Ксенія' 		, en: 'Xenia'		, },
{ ua: 'Лариса'		, en: 'Larisa' 		, },
{ ua: 'Лев' 		, en: 'Lev' 		, p: [{ ua: 'Львівна' 		, en: 'Lvovna' 			, }, { ua: 'Львович' 		, en: 'Lvovich' 		, }, ], },
{ ua: 'Леван' 		, en: 'Levan' 		, p: [{ ua: 'Леванівна' 	, en: 'Levanovna' 		, }, { ua: 'Леванович' 		, en: 'Levanovich' 		, }, ], },
{ ua: 'Леонід' 		, en: 'Leonid' 		, p: [{ ua: 'Леонідівна' 	, en: 'Leonidovna' 		, }, { ua: 'Леонідович' 	, en: 'Leonidovich' 	, }, ], },
{ ua: 'Ліана' 		, en: 'Liana' 		, },
{ ua: 'Лідія' 		, en: 'Lidia' 		, },
{ ua: 'Лілія' 		, en: 'Lilia' 		, },
{ ua: 'Лінв' 		, en: 'Lina' 		, },
{ ua: 'Лія' 		, en: 'Lia' 		, },
{ ua: 'Любов' 		, en: 'Lyubov' 		, },
{ ua: 'Людмила' 	, en: 'Lyudmila' 	, },
{ ua: 'Максим' 		, en: 'Maxim' 		, p: [{ ua: 'Максимівна' 	, en: 'Maximovna' 		, }, { ua: 'Максимович' 	, en: 'Maximovich' 		, }, ], },
{ ua: 'Марат' 		, en: 'Marat' 		, p: [{ ua: 'Маратівна' 	, en: 'Maratovna' 		, }, { ua: 'Маратович' 		, en: 'Maratovich' 		, }, ], },
{ ua: 'Марина' 		, en: 'Marina' 		, },
{ ua: 'Марія' 		, en: 'Maria' 		, },
{ ua: 'Марк' 		, en: 'Mark'		, p: [{ ua: 'Марківна' 		, en: 'Markovna' 		, }, { ua: 'Маркович' 		, en: 'Markovich' 		, }, ], },
{ ua: 'Мар\'яна' 	, en: 'Maryana' 	, },
{ ua: 'Митрофан' 	, en: 'Mitrofan' 	, p: [{ ua: 'Митрофанівна' 	, en: 'Mitrofanvna' 	, }, { ua: 'Митрофанович'	, en: 'Mitrofanovich' 	, }, ], },
{ ua: 'Михайло' 	, en: 'Mihail' 		, p: [{ ua: 'Михайлівна' 	, en: 'Mihailovna' 		, }, { ua: 'Михайлович' 	, en: 'Mihailovich' 	, }, ], },
{ ua: 'Надія' 		, en: 'Nadezhda' 	, },
{ ua: 'Настя'		, en: 'Nastya' 		, },
{ ua: 'Наталя' 		, en: 'Natalia' 	, },
{ ua: 'Микитв' 		, en: 'Nikita' 		, p: [{ ua: 'Микитівна' 	, en: 'Nikita' 			, }, { ua: 'Микитович' 		, en: 'Nikitovich' 		, }, ], },
{ ua: 'Микола' 		, en: 'Nikolay' 	, p: [{ ua: 'Миколаївна' 	, en: 'Nikolay' 		, }, { ua: 'Миколайович' 	, en: 'Nikolaevich' 	, }, ], },
{ ua: 'Ніна' 		, en: 'Nina' 		, },
{ ua: 'Нона' 		, en: 'Nona' 		, },
{ ua: 'Оксана' 		, en: 'Oxana' 		, },
{ ua: 'Олег' 		, en: 'Oleg' 		, p: [{ ua: 'Олегівна' 		, en: 'Olegovna' 		, }, { ua: 'Олегович' 		, en: 'Olegovich' 		, }, ], },
{ ua: 'Олеся' 		, en: 'Olesya' 		, },
{ ua: 'Ольга' 		, en: 'Olga' 		, },
{ ua: 'Павло' 		, en: 'Pavel' 		, p: [{ ua: 'Павлівна' 		, en: 'Pavel' 			, }, { ua: 'Павлович' 		, en: 'Pavlovich' 		, }, ], },
{ ua: 'Пауліна' 	, en: 'Paulina' 	, },
{ ua: 'Петро' 		, en: 'Petr' 		, p: [{ ua: 'Петрівна' 		, en: 'Petrovna' 		, }, { ua: 'Петрович' 		, en: 'Petrovich' 		, }, ], },
{ ua: 'Петрос' 		, en: 'Petros' 		, p: [{ ua: 'Петросівна' 	, en: 'Petrosovna' 		, }, { ua: 'Петросович'		, en: 'Petrosovich' 	, }, ], },
{ ua: 'Погос' 		, en: 'Pogos' 		, p: [{ ua: 'Погосівна' 	, en: 'Pogosovna' 		, }, { ua: 'Погосович' 		, en: 'Pogosovich' 		, }, ], },
{ ua: 'Поліна' 		, en: 'Polina' 		, },
{ ua: 'Потап' 		, en: 'Potap' 		, p: [{ ua: 'Потапівна' 	, en: 'Potapvna' 		, }, { ua: 'Потапович' 		, en: 'Potapovich' 		, }, ], },
{ ua: 'Прокофій' 	, en: 'Prokofy' 	, p: [{ ua: 'Прокопівна' 	, en: 'Prokofevna' 		, }, { ua: 'Прокопович' 	, en: 'Prokofevich' 	, }, ], },
{ ua: 'Размік' 		, en: 'Razmik' 		, p: [{ ua: 'Размиківна' 	, en: 'Razmikvna' 		, }, { ua: 'Размикович' 	, en: 'Razmikovich' 	, }, ], },
{ ua: 'Рита' 		, en: 'Rita' 		, },
{ ua: 'Роман' 		, en: 'Roman' 		, p: [{ ua: 'Романівна' 	, en: 'Romanovna' 		, }, { ua: 'Романович' 		, en: 'Romanovich'		, }, ], },
{ ua: 'Ростислав' 	, en: 'Rostislav' 	, p: [{ ua: 'Ростиславівна' , en: 'Rostislavovna' 	, }, { ua: 'Ростиславович' 	, en: 'Rostislavovich' 	, }, ], },
{ ua: 'Руслан' 		, en: 'Ruslan'		, p: [{ ua: 'Русланівна' 	, en: 'Ruslanovoa' 		, }, { ua: 'Русланович' 	, en: 'Ruslanovich' 	, }, ], },
{ ua: 'Рустам' 		, en: 'Rustam' 		, p: [{ ua: 'Рустамівна' 	, en: 'Rustamovna' 		, }, { ua: 'Рустамович' 	, en: 'Rustamovich' 	, }, ], },
{ ua: 'Савелій' 	, en: 'Savely' 		, p: [{ ua: 'Савельївна' 	, en: 'Savely' 			, }, { ua: 'Савельєвич' 	, en: 'Savelevich' 		, }, ], },
{ ua: 'Саркіс' 		, en: 'Sarkisovich' , p: [{ ua: 'Саркісівна' 	, en: 'Sarkisovna' 		, }, { ua: 'Саркисович' 	, en: 'Sarkisovich' 	, }, ], },
{ ua: 'Світлана' 	, en: 'Svetlana' 	, },
{ ua: 'Семен' 		, en: 'Semen' 		, p: [{ ua: 'Семенівна' 	, en: 'Semenovna' 		, }, { ua: 'Семенович' 		, en: 'Semenovich' 		, }, ], },
{ ua: 'Сергій' 		, en: 'Sergey' 		, p: [{ ua: 'Сергіївна' 	, en: 'Sergeevna' 		, }, { ua: 'Сергійович' 	, en: 'Sergeevich' 		, }, ], },
{ ua: 'Сніжана' 	, en: 'Snezhana' 	, },
{ ua: 'Спартак' 	, en: 'Spartak' 	, p: [{ ua: 'Спартаківна' 	, en: 'Spartakovna' 	, }, { ua: 'Спартакович' 	, en: 'Spartakovich' 	, }, ], },
{ ua: 'Станіслав' 	, en: 'Stanislav' 	, p: [{ ua: 'Станіславівна' , en: 'Stanislavovna' 	, }, { ua: 'Станіславович' 	, en: 'Stanislavovich' 	, }, ], },
{ ua: 'Степан' 		, en: 'Stepan' 		, p: [{ ua: 'Степанівна' 	, en: 'Stepanovna' 		, }, { ua: 'Степанович' 	, en: 'Stepanovich' 	, }, ], },
{ ua: 'Таймураз' 	, en: 'Taymuraz' 	, p: [{ ua: 'Таймуразівна' 	, en: 'Taymurazovna' 	, }, { ua: 'Таймуразович' 	, en: 'Taymurazovich' 	, }, ], },
{ ua: 'Таліко' 		, en: 'Taliko' 		, },
{ ua: 'Тамаз' 		, en: 'Tamaz' 		, p: [{ ua: 'Тамазівна' 	, en: 'Tamazovna' 		, }, { ua: 'Тамазович' 		, en: 'Tamazovich' 		, }, ], },
{ ua: 'Тамара' 		, en: 'Tamara' 		, },
{ ua: 'Таміла' 		, en: 'Tamila' 		, },
{ ua: 'Тарієл' 		, en: 'Tariel' 		, p: [{ ua: 'Тарієлович' 	, en: 'Tarielovich' 	, }, { ua: 'Тарієлович' 	, en: 'Tarielovich' 	, }, ], },
{ ua: 'Тетяна' 		, en: 'Tatyana' 	, },
{ ua: 'Тіматі' 		, en: 'Timati' 		, p: [{ ua: 'Тіматіївна' 	, en: 'Timatevna' 		, }, { ua: 'Тіматович' 		, en: 'Timatevich' 		, }, ], },
{ ua: 'Тимофій' 	, en: 'Timofey' 	, p: [{ ua: 'Тимофіївна' 	, en: 'Timofeevna' 		, }, { ua: 'Тимофійович' 	, en: 'Timofeevich'		, }, ], },
{ ua: 'Тимур' 		, en: 'Timur' 		, p: [{ ua: 'Тимурівна' 	, en: 'Timurovna' 		, }, { ua: 'Тимурович' 		, en: 'Timurovich' 		, }, ], },
{ ua: 'Уляна' 		, en: 'Ulyana' 		, },
{ ua: 'Фаб\'єн' 	, en: 'Fabienne' 	, p: [{ ua: 'Фаб\'єнівна' 	, en: 'Fabienovna' 		, }, { ua: 'Фаб\'єнович' 	, en: 'Fabienovich' 	, }, ], },
{ ua: 'Фатіма' 		, en: 'Fatima' 		, },
{ ua: 'Федір' 		, en: 'Fedor' 		, p: [{ ua: 'Федірівна' 	, en: 'Fedorovna' 		, }, { ua: 'Федорович' 		, en: 'Fedorovich' 		, }, ], },
{ ua: 'Фрунзік' 	, en: 'Frunzik' 	, p: [{ ua: 'Фрунзиківна' 	, en: 'Frunzikovna' 	, }, { ua: 'Фрунзікович' 	, en: 'Frunzikovich' 	, }, ], },
{ ua: 'Христос' 	, en: 'Hristos' 	, p: [{ ua: 'Христосівна' 	, en: 'Hristosovna' 	, }, { ua: 'Христосович' 	, en: 'Hristosovich' 	, }, ], },
{ ua: 'Шодавлат' 	, en: 'Shodavlat' 	, p: [{ ua: 'Шодавлатівна' 	, en: 'Shodavlatovna' 	, }, { ua: 'Шодавлатович' 	, en: 'Shodavlatovich' 	, }, ], },
{ ua: 'Евеліна' 	, en: 'Evelina' 	, },
{ ua: 'Едуард' 		, en: 'Eduard' 		, p: [{ ua: 'Едуардівна' 	, en: 'Eduardovna' 		, }, { ua: 'Едуардович' 	, en: 'Eduardovich' 	, }, ], },
{ ua: 'Еліна' 		, en: 'Elina' 		, },
{ ua: 'Ельдар' 		, en: 'Eldar' 		, p: [{ ua: 'Ельдарівна' 	, en: 'Eldarovna' 		, }, { ua: 'Ельдарович' 	, en: 'Eldarovich' 		, }, ], },
{ ua: 'Еміль' 		, en: 'Emil' 		, p: [{ ua: 'Емільївна' 	, en: 'Emilevna' 		, }, { ua: 'Емільйович' 	, en: 'Emilevich' 		, }, ], },
{ ua: 'Етьєн' 		, en: 'Etienne' 	, p: [{ ua: 'Етьєнівна' 	, en: 'Etienovna' 		, }, { ua: 'Етьєнович' 		, en: 'Etienovich' 		, }, ], },
{ ua: 'Юлія' 		, en: 'Julia' 		, },
{ ua: 'Юрій' 		, en: 'Jury' 		, p: [{ ua: 'Юріївна' 		, en: 'Jurevna' 		, }, { ua: 'Юрійович' 		, en: 'Jurevich' 		, }, ], },
{ ua: 'Юсуп' 		, en: 'Jusup' 		, p: [{ ua: 'Юсупівна' 		, en: 'Jusupovna' 		, }, { ua: 'Юсупівна' 		, en: 'Jusupovna' 		, }, ], },
{ ua: 'Ян' 			, en: 'Yan' 		, p: [{ ua: 'Янівна' 		, en: 'Yanovna' 		, }, { ua: 'Янович' 		, en: 'Yanovich' 		, }, ], },
{ ua: 'Яна' 		, en: 'Yana' 		, },
{ ua: 'Ярослав' 	, en: 'Yaroslav' 	, p: [{ ua: 'Ярославівна' 	, en: 'Yaroslavovna' 	, }, { ua: 'Ярославович' 	, en: 'Yaroslavovich' 	, }, ], },
{ ua: 'Ярослава' 	, en: 'Yaroslava' 	, },




/*

{ en: 'Alex' 	, },
{ en: 'Bill' 	, },
{ en: 'Brian' 	, },
{ en: 'Gary' 	, },
{ en: 'Henry' 	, },
{ en: 'Daniel' 	, },
{ en: 'James' 	, },
{ en: '' 	, },
{ en: '' 	, },
{ en: '' 	, },
{ en: '' 	, },





'Алекс', 
'Билл', 
'Боб', 
'Брайн', 
'Гарри', 
'Генри', 
'Даниэль', 
'Джеймс', 
'Джек', 
'Джерри', 
'Джозеф', 
'Джон', 
'Джордж', 
'Дональд', 
'Дэвид', 
'Итан', 
'Кевин', 
'Кен', 
'Кристофер', 
'Майкл', 
'Микки', 
'Николас', 
'Оливер', 
'Патрик', 
'Питер', 
'Пол', 
'Роберт', 
'Робин', 
'Стивен', 
'Сэм', 
'Том', 
'Фрэнк', 
'Эндрю', 
'Энтони', 

'Анжела', 
'Ариэль', 
'Барбара', 
'Бренда', 
'Ванесса', 
'Грета', 
'Дженнифер', 
'Джессика', 
'Джуди', 
'Джулиана', 
'Джулия', 
'Кейт', 
'Кэтрин', 
'Линда', 
'Лора', 
'Люси', 
'Маргарет', 
'Матильда', 
'Моника', 
'Николь', 
'Нэнси', 
'Патрисия', 
'Сандра', 
'Сара', 
'Синтия', 
'Сьюзан', 
'Тина', 
'Шэрон', 
'Элизабет', 
'Эльза', 
'Эмилия', 
'Эмма',

*/


];

